# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"

image:
  repository: quay.io/noesamaille0/ascent-injector
  tag: 0.0.1
  pullPolicy: IfNotPresent

partOf: "ascent"

connectsTo: "ascent-mongodb"
